openapi: 3.0.3
info:
  version: 1.2.0
  title: Hanko Admin Audit Logs Status API
  description: '## Introduction


    This is the OpenAPI specification for the [Hanko Admin API](https://github.com/teamhanko/hanko/blob/main/backend/README.md#start-private-api).


    ## Authentication


    The Admin API must be protected by an access management system.


    ---

    '
  contact:
    email: developers@hanko.io
  license:
    name: AGPL-3.0-or-later
    url: https://www.gnu.org/licenses/agpl-3.0.txt
servers:
- url: https://{tenant_id}.hanko.io/admin
  variables:
    tenant_id:
      default: ''
      description: The (UU)ID of a tenant. Replace the default value with your tenant ID.
tags:
- name: Status
paths:
  /:
    get:
      summary: Status page
      description: Return information about the API status. Returns a 500 if there are issues with database connectivity.
      security:
      - BearerApiKeyAuth: []
      operationId: status
      tags:
      - Status
      responses:
        '200':
          description: API is running
          content:
            text/html:
              schema:
                type: string
        '500':
          description: API is not functioning properly
          content:
            text/html:
              schema:
                type: string
components:
  securitySchemes:
    BearerApiKeyAuth:
      description: Bearer authentication header of the form `Bearer <token>`, where `<token>` is your API key. Must only be used when using Hanko Cloud.
      type: http
      scheme: bearer
      bearerFormat: API Key
externalDocs:
  description: More about Hanko
  url: https://github.com/teamhanko/hanko
